language: python
dist: bionic
addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c 'create extension postgis'
python:
  - 3.6
  - 3.7
env:
  - DJANGO=3.0
before_install:
  - export DJANGO_SETTINGS_MODULE="cts.settings.travis"
  - export DEBUG=True
install:
  - pip install coverage
  - pip install coveralls
  - pip install -r cts/requirements.txt
  - sudo apt-get install binutils libproj-dev gdal-bin
script:
  - cd cts
  - coverage run manage.py test --keepdb
after_success:
  - coverage report
  - coveralls
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: VZ7/Cr2UDAFegIMKZrknEAWPS29DSYktGv8VjbccbY0STK7bvDlwMOaDWjJglizTG121OXPOegYwQLQL2c85f7u2bLeAXNruTe7JPxYXhS/FboLUihj7JE3cam7Ru0OUNpVIU6voVR831GF4xgwMzzLgZWB+dDKuOHhu/a83v9R/EmNFaPak8SWxO29CLHugALxByi8Y9w7o/Ijxn0CASau752OgV5uCsYI+e8+d+TCEYqMnu8m9qIbFyQyTTzJ34m4xQ+UHYi6+nUOlLp57LonnPhF7QZTFrLatD0JTr+mYTC5DMb2x6cjgVpyieggNvzAth8ciUQkpYtXqUy68ixS1Kw4SkxPkH+XiIrZc07hPWuZZONTCZilowiHcEWhwqM/OjalzIQh9lTBXTIBj/RR8FG7+fxrIwnkDN+tGm+CzM7K3Q/3sL6i65CScRjaIg01ykPZJeKCrLxZbAzHSxYDhHYD1WIpkVz4sB+DJzdwqH5VH89HJbgXfjus6OrxEnvHhRTRuKwjkSAsbomrYoCYrFIUc7xapp0BOl12ms/KCh90bic+Nnv/sVYFWw8OkZfIsSIyexyXrMYcJbDQYaIm8cxV3HdrZdUuHUxYmXzRc2J1EOkXHjpz3DFUcQsKWZytf2Wvl6VttTXpY6znLk2HT+1h5LrvQJp5wFF73bbg=
