language: python
python:
  - 3.5
  - 3.6
services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  - DJANGO_SETTINGS_MODULE="cts.settings.travis"
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -c 'CREATE SCHEMA postgis;' -U postgres -d travis_ci_test
  - psql -c 'CREATE EXTENSION postgis SCHEMA postgis;' -U postgres -d travis_ci_test
  - psql -c 'CREATE EXTENSION pgrouting;' -U postgres -d travis_ci_test
  - cd cts
install:
  - pip install -r requirements.txt
script:
  - manage.py test
notifications:
  email:
    on_success: change
    on_failure: always