version: '3'

services:
  # PostGIS database
  db:
    env_file: /opt/db_secrets.env
    image: my_postgis

  # Redis
  redis:
    image: redis:3.2.11
    hostname: redis

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.7.2
    env_file: /opt/rabbit_secrets.env
    ports:
      - "5672:5672"
      - "15672:15672"

  # Django web server
  web:
    build: .
    env_file: /opt/django_secrets.env
    command: ./run_web.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - db

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: /opt/django_secrets.env
    command: ./run_celery.sh
    volumes:
      - .:/code
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - rabbit