version: '3'

services:
  db:
    env_file: /opt/db_secrets.env
    image: my_postgis
  web:
    build: .
    env_file: /opt/django_secrets.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db