version: '3'

services:
  # PostGIS database
  db:
    restart: always
    env_file: /opt/db_secrets.env
    build: ../postgis

  # Redis
  redis:
    restart: always
    image: redis:3.2.11
    hostname: redis
    expose:
      - "6379"

  # RabbitMQ
  rabbit:
    restart: always
    hostname: rabbit
    image: rabbitmq:3.7.2
    env_file: /opt/rabbit_secrets.env
    ports:
      - "5672:5672"
      - "15672:15672"

  # Django web server
  web:
    restart: always
    build: .
    env_file: /opt/django_secrets.env
    command: ./run_web.sh
    volumes:
      - static:/code/static
      - media:/code/media
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - db
    ports:
      - "8000:8000"

  # Celery worker
  worker:
    restart: always
    build: .
    env_file: /opt/django_secrets.env
    command: ./run_celery.sh
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - rabbit

volumes:
  static:
  media: